### ISSUE TITLE
Curses should use `curses.wrapper()`

### ISSUE THREAD

**Issue by tman540** [jazztickets/terminalheroes#1]
When the game unexpectedly exits, the window is not properly exited and the terminal is left broken. The curses window should be used with `curses.wrapper()` so if the program exits unexpectedly (ex: if the user pressed CTRL+C), the terminal will be left in a normal state.

**Comment by jazztickets** [comment]
I'll see what i can do

**Comment by jazztickets** [comment]
I couldn't figure out why curses.wrapper was messing with the input handler (certain keys stopped working), so instead I just made ctrl+c exit gracefully.
